## Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [33]:
a=np.arange(1,10)
b=a[a%2!=0].copy()
b

array([1, 3, 5, 7, 9])

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [35]:
a=np.arange(1,10)
a[a%2!=0]=0
a

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [17]:
data = np.genfromtxt('iris.data', delimiter=',', usecols=[0,1,2,3])
print(data[:10,:])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [18]:
np.mean(data[:,0])

5.843333333333334

In [24]:
np.median(data[:,0])

5.8

In [19]:
np.std(data[:,0])

0.8253012917851409

5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [25]:
data[(data[:,2]>1.5)&(data[:,0]<5)]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

6 - Esse dataset possui nans?

In [27]:
np.any(np.isnan(data))

False

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [62]:
np.set_printoptions(suppress=True)
vol=((np.pi)*(data[:,2])*((data[:,0])**2))/3
vol=vol.reshape((-1,1))
fulldata=np.hstack((data,vol))
print(np.round(fulldata,2)

[[  5.1    3.5    1.4    0.2   38.13]
 [  4.9    3.     1.4    0.2   35.2 ]
 [  4.7    3.2    1.3    0.2   30.07]
 [  4.6    3.1    1.5    0.2   33.24]
 [  5.     3.6    1.4    0.2   36.65]
 [  5.4    3.9    1.7    0.4   51.91]
 [  4.6    3.4    1.4    0.3   31.02]
 [  5.     3.4    1.5    0.2   39.27]
 [  4.4    2.9    1.4    0.2   28.38]
 [  4.9    3.1    1.5    0.1   37.71]
 [  5.4    3.7    1.5    0.2   45.8 ]
 [  4.8    3.4    1.6    0.2   38.6 ]
 [  4.8    3.     1.4    0.1   33.78]
 [  4.3    3.     1.1    0.1   21.3 ]
 [  5.8    4.     1.2    0.2   42.27]
 [  5.7    4.4    1.5    0.4   51.04]
 [  5.4    3.9    1.3    0.4   39.7 ]
 [  5.1    3.5    1.4    0.3   38.13]
 [  5.7    3.8    1.7    0.3   57.84]
 [  5.1    3.8    1.5    0.3   40.86]
 [  5.4    3.4    1.7    0.2   51.91]
 [  5.1    3.7    1.5    0.4   40.86]
 [  4.6    3.6    1.     0.2   22.16]
 [  5.1    3.3    1.7    0.5   46.3 ]
 [  4.8    3.4    1.9    0.2   45.84]
 [  5.     3.     1.6    0.2   41.89]
 [  5.     3